name: "test"
on:
  pull_request:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOK }}
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: info  
        run: |
          echo $GITHUB_REPOSITORY
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_BASE_REF
                
  analyze:
    uses: tonasodji/pvs/.github/workflows/test.yml@main
