name: ssh command
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: 192.168.108.128
          SSH_PORT: 20
          SSH_USER: aime
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: |
        ssh ${{ steps.ssh.outputs.SERVER }} pwd
        pvs-studio --version
